# Makefile for Win32

TOP = ..\..

!ifdef WOA
!include "$(TOP)\woa.mak"
!else
!include <win32.mak>
!endif

EXTRACFLAGS = -DOPENGL_10 -DAUTO_TEXTURE -D__GUTIL_DOUBLE

SRCS = ex_angle.c ex_cut_round.c ex_raw.c extrude.c intersect.c rot_prince.c rotate.c round_cap.c segment.c texgen.c urotate.c view.c
OBJS = $(SRCS:.c=.obj)

all	: gle.lib

!include "$(TOP)/glutwin32.mak"

gle.lib	: $(OBJS)
	$(implib) -out:gle.lib $(OBJS)
