# Makefile for Win32
# Copyright (c) Mark J. Kilgard, 1997.

TOP = ..\..

!ifdef WOA
!include "$(TOP)\woa.mak"
!else
!include <win32.mak>
!endif

SRCS = asteroids.c

!include "$(TOP)/glutwin32.mak"

# dependencies
