# Makefile for Win32

TOP = ..\..

!ifdef WOA
!include "$(TOP)\woa.mak"
!else
!include <win32.mak>
!endif

SRCS = mui_test.c multi_test.c

EXTRALIBS = $(MUI)
DEPLIBS = $(MUI)

!include "$(TOP)/glutwin32.mak"

test : mui_test.exe multi_test.exe
