# Makefile for Win32

TOP = ..\..

!ifdef WOA
!include "$(TOP)\woa.mak"
!else
!include <win32.mak>
!endif

SRCS = showtxf.c txfdemo.c simpletxf.c

!include "$(TOP)/glutwin32.mak"

# dependencies
txfdemo.exe	\
simpletxf.exe	\
showtxf.exe	: texfont.obj
