#
# $Header: //sw/apps/gpu/drivers/opengl/glut/include/GNUmakefile#1 $
#

# Don't mangle symbols in GLUT
MANGLE_SYMBOLS = 0

include $(ROOT)/usr/include/make/commondefs

default:

install headers_install:
	$(INSTALL) -F $(INCLUDE_LOCATION)/GL -f glut.h GL/glut.h

include $(COMMONRULES)
